### ISSUE TITLE
fiv-loading-content problem with overflow-x scroll

### ISSUE THREAD

**Issue by paulovargatt** [fivethree-team/ionic-4-components#137]
Hello,
Congratulations to all involved for the excellent work!

I'm finding some problems with the component 'fiv-loading-content', in my app I have a box with overflow-x: scroll, the component left this box unusable ie the user can not drag the box anymore because the component is by above, I tried to put z-index in the component and box but without success.

I believe the component should not check horizontal events

![fiv-loading](https://user-images.githubusercontent.com/28814403/59041631-62080f00-884f-11e9-8fb2-73cb989e48c4.jpg)

**Comment by garygrossgarten** [comment]
Hi @paulovargatt ,

thank you for your feedback! :)

I'm not super happy with the implementation of the refresher right now. (It's also kind of buggy on ios). I've planned to change it up for version 1.0.0 to better match the api of the ion-refresher. Hopefully this will fix your problem too.

If you have an idea to improve the component feel free to submit a PR. For now you could share a repo with you implementation of the `fiv-loading-content` so that i can understand your problem better.

Cheers,

Gary

**Comment by paulovargatt** [comment]
Ok @garygrossgarten ,
Sorry for the delay in responding.

[repository by illustrating the problem](https://github.com/paulovargatt/fiv-loading-content-tests/blob/master/src/app/home/home.page.html)

**Comment by garygrossgarten** [comment]
Hey @paulovargatt sorry for letting you wait so long.
I just sent you a PR for your test repo updating the `@fivethree/core`dependency to the latest release. I marked all the touch handlers for the pull down as passive. This should fix the problem but please test it out yourself and report here.

Cheers

**Comment by paulovargatt** [comment]
thank you,
For my need (Android) worked well!
I still need to see it on IOS ...
Thanks for the work;)

**Comment by paulovargatt** [comment]
Hello @garygrossgarten,
in tests in the browser the animation has the correct operation, except when scrolling on the page because the content rolls even with the active "pull" animation.

In tests on the android device, the animation seems very slow, perhaps because of the page scroll event happen as well.
